DROP TABLE IF EXISTS tab;
DROP TABLE IF EXISTS sess;

CREATE TABLE tab (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sess INTEGER NOT NULL,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  state INT NOT NULL, /* 0 is default state, 1 means "locked" */
  UNIQUE(sess, url) ON CONFLICT REPLACE
);

CREATE TABLE sess (
  id INTEGER PRIMARY KEY ON CONFLICT REPLACE,
  name TEXT NOT NULL
);


